In [2]:
import torch
gpu_avail = torch.cuda.is_available()
print(f"Is the GPU available? {gpu_avail}")

Is the GPU available? False


In [6]:
a = torch.rand(2,2)
print(a)
b = torch.rand(2,2)
c = a + b
d = torch.add(a,b)
print(d)

tensor([[0.4799, 0.7258],
        [0.5562, 0.5684]])
tensor([[0.9760, 1.4975],
        [0.7211, 0.9627]])


In [25]:
import numpy as np
l=[2,3,4,5]
a=np.array(l)
a

array([2, 3, 4, 5])

In [29]:
a=torch.tensor([5,6,7],dtype=torch.float)
b=torch.tensor([1,2,3],dtype=torch.float)
print(a+b)
f=torch.zeros(2,3,dtype=torch.float64)
print(f)

tensor([ 6.,  8., 10.])
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [30]:
torch.add(b,a,out=c)
print(c)

tensor([ 6.,  8., 10.])


C:\Users\dllab.DLL-040\AppData\Local\Temp\ipykernel_10668\571966660.py:1: UserWarning: An output with one or more elements was resized since it had shape [2, 2], which does not match the required output shape [3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ..\aten\src\ATen\native\Resize.cpp:24.)
  torch.add(b,a,out=c)


In [35]:
torch.add(a,b).sum()
a=torch.tensor([4,5]) 
b=torch.tensor([2,3]) 
a.mul(b)
a.dot(b)

tensor(23)