In [16]:
# Implementing KSOM For Iris Dataset

import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import pandas as pd
df = pd.read_csv("/content/Pistachio_28_Features_Dataset.csv")
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x = scaler.fit_transform(x)
class KSOM(nn.Module):

    def __init__(self, input_dim, output_dim):
        super(KSOM, self).__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.weights = torch.randn(input_dim,output_dim)

    def forward(self, x):
        distances = torch.sum((x - self.weights)**2, axis=1)
        winner = torch.argmin(distances)
        return winner
    
    def weight_updation(self, x, winner, lr=0.02):
        d = x
        for i in range(self.output_dim):
            if i == winner:
                self.weights[i] += lr * d[i]
            return self.weights[i]
model = KSOM(input_dim=28, output_dim=28)
for epoch in range(2):
    for o in x:
        o = torch.Tensor(o)
        winner = model(o)
        print(model.weight_updation(o, winner, lr=0.2))

Streaming output truncated to the last 5000 lines.
tensor([ 0.8495,  0.2961,  1.5257,  0.7112,  0.6627,  0.9958,  1.4399,  0.8962,
         1.8270,  1.5413,  1.3229,  1.6877,  1.1945, -0.2284,  1.1672,  0.8562,
         0.9649,  0.3955,  2.9735, -0.1353,  1.1142, -0.2560,  0.6170,  1.5775,
         1.7248,  1.3577,  2.3460, -0.0807])
tensor([ 0.8495,  0.2961,  1.5257,  0.7112,  0.6627,  0.9958,  1.4399,  0.8962,
         1.8270,  1.5413,  1.3229,  1.6877,  1.1945, -0.2284,  1.1672,  0.8562,
         0.9649,  0.3955,  2.9735, -0.1353,  1.1142, -0.2560,  0.6170,  1.5775,
         1.7248,  1.3577,  2.3460, -0.0807])
tensor([ 0.8495,  0.2961,  1.5257,  0.7112,  0.6627,  0.9958,  1.4399,  0.8962,
         1.8270,  1.5413,  1.3229,  1.6877,  1.1945, -0.2284,  1.1672,  0.8562,
         0.9649,  0.3955,  2.9735, -0.1353,  1.1142, -0.2560,  0.6170,  1.5775,
         1.7248,  1.3577,  2.3460, -0.0807])
tensor([ 0.8495,  0.2961,  1.5257,  0.7112,  0.6627,  0.9958,  1.4399,  0.8962,
         1.827