In [ ]:
import numpy as np
def sig(x):
 return 1/(1 + np.exp(-x))
def perceptronModel(x, w, b):
    v = np.dot(w, x) + b
    y = sig(v)
    return y
def OR_logicFunction(x):
    w = np.array([1, 1])
    b = -0.5
    return perceptronModel(x, w, b)
test1 = np.array([0, 1])
test2 = np.array([1, 1])
test3 = np.array([0, 0])
test4 = np.array([1, 0])
  
print("OR({}, {}) = {}".format(0, 1, OR_logicFunction(test1)))
print("OR({}, {}) = {}".format(1, 1, OR_logicFunction(test2)))
print("OR({}, {}) = {}".format(0, 0, OR_logicFunction(test3)))
print("OR({}, {}) = {}".format(1, 0, OR_logicFunction(test4)))


OR(0, 1) = 0.6224593312018546
OR(1, 1) = 0.8175744761936437
OR(0, 0) = 0.3775406687981454
OR(1, 0) = 0.6224593312018546


In [ ]:
import numpy as np
import pandas as pd 

class Perceptron:
  def __init__(self, lr, epochs):
    self.weights = np.random.randn(3) 
    print(f"initial weights before training: n{self.weights}")
    self.lr = lr
    self.epochs = epochs 


  def activationFunction(self, inputs, weights):
    z = np.dot(inputs, weights) 
    return np.where(z > 0, 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] 
    print(f"X with bias: n{X_with_bias}")

    for epoch in range(self.epochs):
      print("--"*10)
      print(f"for epoch: {epoch}")
      print("--"*10)

      y_hat = self.activationFunction(X_with_bias, self.weights) 
      print(f"predicted value: n{y_hat}")
      self.error = self.y - y_hat
      print(f"error: n{self.error}")
      self.weights = self.weights + self.lr * np.dot(X_with_bias.T, self.error) 


  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(X), 1))]
    return self.activationFunction(X_with_bias, self.weights)

  def total_loss(self):
    total_loss = np.sum(self.error)
    print(f"total loss: {total_loss}")
    return total_loss


OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,1,1,1],
}
df = pd.DataFrame(OR)
X=df.drop("y",axis=1)
y=df["y"]
print(X)
LR = 0.3 
EPOCHS = 10

model = Perceptron(lr=LR, epochs=EPOCHS)
model.fit(X, y)

model.total_loss()

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1
initial weights before training: n[ 6.36684346e-05 -1.59790855e-04 -1.92702184e-04]
X with bias: n[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch: 0
--------------------
predicted value after forward pass: n[1 1 1 1]
error: n0   -1
1    0
2    0
3    0
Name: y, dtype: int64
--------------------
for epoch: 1
--------------------
predicted value after forward pass: n[0 0 0 0]
error: n0    0
1    1
2    1
3    1
Name: y, dtype: int64
--------------------
for epoch: 2
--------------------
predicted value after forward pass: n[1 1 1 1]
error: n0   -1
1    0
2    0
3    0
Name: y, dtype: int64
--------------------
for epoch: 3
--------------------
predicted value after forward pass: n[1 1 1 1]
error: n0   -1
1    0
2    0
3    0
Name: y, dtype: int64
--------------------
for epoch: 4
--------------------
predicted value after forward pass: n[1 1 1 1]
error: n0   -1
1    0
2    0
3    0
Name: y, dtyp

0